//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int ProductFk { get; set; }
        public System.DateTime DatePlaced { get; set; }
        public int Qty { get; set; }
        public bool Paid { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
